package programa;

import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.ImageIcon;

public class VPrincipal extends javax.swing.JFrame {

    public VPrincipal() {
        //Inicialización de los componentes por parte de netbeans (Tamaños, posición...)
        initComponents();
        //inicialización de los componentes por nuestra parte (Títulos, iconos...)
        iniciar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarcoPrincipal = new javax.swing.JPanel();
        Pantalla = new javax.swing.JTextField();
        jButtonBorrar = new javax.swing.JButton();
        jButtonBackSpace = new javax.swing.JButton();
        jButtonCopiar = new javax.swing.JButton();
        jButtonPegar = new javax.swing.JButton();
        jPanelTeclas = new javax.swing.JPanel();
        jPanelOperacionesNumeros = new javax.swing.JPanel();
        jPanelDigitos = new javax.swing.JPanel();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonPunto = new javax.swing.JButton();
        jPanelOperaciones = new javax.swing.JPanel();
        jButtonSumar = new javax.swing.JButton();
        jButtonRestar = new javax.swing.JButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jButtonDividir = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jPanelMemoria = new javax.swing.JPanel();
        jButtonVerMemo = new javax.swing.JButton();
        jButtonMMas = new javax.swing.JButton();
        jButtonMMenos = new javax.swing.JButton();
        jButtonMBorrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonPi = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonAureo = new javax.swing.JButton();
        jButtonEuler = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora - Borjaro2000.tk");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        Pantalla.setEditable(false);
        Pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Pantalla.setText("0");
        Pantalla.setAutoscrolls(false);
        Pantalla.setMinimumSize(new java.awt.Dimension(12, 20));

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonBackSpace.setText("<-");
        jButtonBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackSpaceActionPerformed(evt);
            }
        });

        jButtonCopiar.setText("Copiar");
        jButtonCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopiarActionPerformed(evt);
            }
        });

        jButtonPegar.setText("Pegar");
        jButtonPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPegarActionPerformed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonPunto.setText(".");
        jButtonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDigitosLayout = new javax.swing.GroupLayout(jPanelDigitos);
        jPanelDigitos.setLayout(jPanelDigitosLayout);
        jPanelDigitosLayout.setHorizontalGroup(
            jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDigitosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDigitosLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addGroup(jPanelDigitosLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanelDigitosLayout.createSequentialGroup()
                        .addGroup(jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDigitosLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDigitosLayout.setVerticalGroup(
            jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDigitosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(6, 6, 6)
                .addGroup(jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDigitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0)
                    .addComponent(jButtonPunto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSumar.setText("+");
        jButtonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarActionPerformed(evt);
            }
        });

        jButtonRestar.setText("-");
        jButtonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestarActionPerformed(evt);
            }
        });

        jButtonMultiplicar.setText("x");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });

        jButtonDividir.setText("/");
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOperacionesLayout = new javax.swing.GroupLayout(jPanelOperaciones);
        jPanelOperaciones.setLayout(jPanelOperacionesLayout);
        jPanelOperacionesLayout.setHorizontalGroup(
            jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSumar, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonRestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMultiplicar, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOperacionesLayout.setVerticalGroup(
            jPanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOperacionesLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jButtonDividir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSumar)
                .addContainerGap())
        );

        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOperacionesNumerosLayout = new javax.swing.GroupLayout(jPanelOperacionesNumeros);
        jPanelOperacionesNumeros.setLayout(jPanelOperacionesNumerosLayout);
        jPanelOperacionesNumerosLayout.setHorizontalGroup(
            jPanelOperacionesNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperacionesNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOperacionesNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonIgual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDigitos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelOperacionesNumerosLayout.setVerticalGroup(
            jPanelOperacionesNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperacionesNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOperacionesNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelOperaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDigitos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIgual)
                .addContainerGap())
        );

        jButtonVerMemo.setText("M");
        jButtonVerMemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerMemoActionPerformed(evt);
            }
        });

        jButtonMMas.setText("M+");
        jButtonMMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMMasActionPerformed(evt);
            }
        });

        jButtonMMenos.setText("M-");
        jButtonMMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMMenosActionPerformed(evt);
            }
        });

        jButtonMBorrar.setText("M->0");
        jButtonMBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMemoriaLayout = new javax.swing.GroupLayout(jPanelMemoria);
        jPanelMemoria.setLayout(jPanelMemoriaLayout);
        jPanelMemoriaLayout.setHorizontalGroup(
            jPanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVerMemo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMMas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMMenos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMBorrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMemoriaLayout.setVerticalGroup(
            jPanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerMemo)
                    .addComponent(jButtonMMas)
                    .addComponent(jButtonMMenos)
                    .addComponent(jButtonMBorrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonPi.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButtonPi.setText("π");
        jButtonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiActionPerformed(evt);
            }
        });

        jButtonE.setText("e");
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        jButtonAureo.setText("φ");
        jButtonAureo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAureoActionPerformed(evt);
            }
        });

        jButtonEuler.setText(" γ");
        jButtonEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAureo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEuler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jButtonPi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAureo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEuler)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelTeclasLayout = new javax.swing.GroupLayout(jPanelTeclas);
        jPanelTeclas.setLayout(jPanelTeclasLayout);
        jPanelTeclasLayout.setHorizontalGroup(
            jPanelTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeclasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOperacionesNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTeclasLayout.setVerticalGroup(
            jPanelTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeclasLayout.createSequentialGroup()
                .addGroup(jPanelTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTeclasLayout.createSequentialGroup()
                        .addComponent(jPanelMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelOperacionesNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTeclasLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jButtonApagar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonApagar.setText("Off");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MarcoPrincipalLayout = new javax.swing.GroupLayout(MarcoPrincipal);
        MarcoPrincipal.setLayout(MarcoPrincipalLayout);
        MarcoPrincipalLayout.setHorizontalGroup(
            MarcoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarcoPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MarcoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTeclas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MarcoPrincipalLayout.createSequentialGroup()
                        .addComponent(jButtonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCopiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPegar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBackSpace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonApagar))
                    .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MarcoPrincipalLayout.setVerticalGroup(
            MarcoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarcoPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MarcoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonCopiar)
                    .addComponent(jButtonPegar)
                    .addComponent(jButtonBackSpace)
                    .addComponent(jButtonApagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MarcoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MarcoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        //Al pulsar el botón off la calculadora se cierra
        System.exit(0);
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopiarActionPerformed
        //El botón copiar llama al método que pasa un string al portapapeles pasándole el valor en la pantalla
        copiarAlPortapapeles(Pantalla.getText());
        //Después devolvemos el foco a la ventana. Esta es la que captura las teclas pulsadas.
        //Así podemos usar los botones o el teclado
        this.requestFocus();
    }//GEN-LAST:event_jButtonCopiarActionPerformed

    private void jButtonPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPegarActionPerformed
        //Traemos los datos del portapapeles
        String temp = pegarDelPortapapeles();
        try {
            //Arreglamos las comas y puntos de los decimales para que los acepte java
            //Otros programas pueden utilizar la coma en vez del punto
            temp.replace(',', '.');
            //Si es un número lo copiamos
            Double.parseDouble(temp);
            //Si falla al transformarlo a número no llegará aquí y no se copiará el dato. Por ej, un texto.
            //Lo escribimos en pantalla
            Pantalla.setText(temp);
            //Devolvemos el foco a la ventana para poder usar el teclado.
            this.requestFocus();
        } catch (NumberFormatException ex) {
        }

    }//GEN-LAST:event_jButtonPegarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        //127 es el valor char para la tecla delete (suprimir)
        numeroPulsado((char) 127);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonVerMemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerMemoActionPerformed
        //Copiamos el dato de la memoria en la pantalla
        Pantalla.setText(memoria.toString());

        //Quitar el decimal si es cero para evitar que salga 10.0
        if (Pantalla.getText().endsWith(".0")) {
            Pantalla.setText(Pantalla.getText().substring(0, Pantalla.getText().length() - 2));
        }
    }//GEN-LAST:event_jButtonVerMemoActionPerformed

    private void jButtonMBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMBorrarActionPerformed
        //Reseteamos la memoria
        memoria = 0.0;
    }//GEN-LAST:event_jButtonMBorrarActionPerformed

    private void jButtonMMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMMasActionPerformed
        //Añadimos a la memoria el valor de la pantalla
        memoria += darValorPantalla();
    }//GEN-LAST:event_jButtonMMasActionPerformed

    private void jButtonMMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMMenosActionPerformed
        //Restamos a la memoria el valor de la pantalla
        memoria -= darValorPantalla();
    }//GEN-LAST:event_jButtonMMenosActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        //Al pulsar un botón se envía el caracter a una función que realiza la acción.
        numeroPulsado('0');
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuntoActionPerformed
        numeroPulsado('.');
    }//GEN-LAST:event_jButtonPuntoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        numeroPulsado('1');
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        numeroPulsado('2');
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        numeroPulsado('3');
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        numeroPulsado('4');
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        numeroPulsado('5');
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        numeroPulsado('6');
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        numeroPulsado('7');
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        numeroPulsado('8');
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        numeroPulsado('9');
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        numeroPulsado('=');
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
        numeroPulsado('/');
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed
        numeroPulsado('*');
    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

    private void jButtonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestarActionPerformed
        numeroPulsado('-');
    }//GEN-LAST:event_jButtonRestarActionPerformed

    private void jButtonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarActionPerformed
        numeroPulsado('+');
    }//GEN-LAST:event_jButtonSumarActionPerformed

    private void jButtonBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackSpaceActionPerformed
        //Este el el valor para BackSpace. La tecla encima del Enter. Que borra el último caracter.
        numeroPulsado('\b');
    }//GEN-LAST:event_jButtonBackSpaceActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        //Este método es el captura la tecla pulsada sobre el elemento que tenga el foco.
        //En este caso es para la ventana
        numeroPulsado(evt.getKeyChar());
    }//GEN-LAST:event_formKeyTyped
    //Forma de detectar el Control+C y Control+V
    //Para comprobar si han pulsado control + algo
    boolean controlPulsado = false;
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //Para control+c y control+v
        if (evt.getKeyCode() == KeyEvent.VK_CONTROL) {//Valor para la tecla control
            //Si la tecla que se detecta es control. Se activa el boleano
            controlPulsado = true;
        } else {
            //Si no es control será la C o la V
            if (controlPulsado && evt.getKeyCode() == KeyEvent.VK_C) {
                //Como no es el control. Lo desactivamos
                controlPulsado = false;
                //Realizamos la acción
                copiarAlPortapapeles(Pantalla.getText());
            } else if (controlPulsado && evt.getKeyCode() == KeyEvent.VK_V) {
                controlPulsado = false;
                //Traemos los datos del portapapeles
                String temp = pegarDelPortapapeles();
                if (temp.length() > 0) {
                    try {
                        //Arreglamos las comas y puntos de los decimales para que los acepte java
                        temp.replace(',', '.');
                        //Si es un número lo copiamos
                        Double.parseDouble(temp);
                        //Si falla al transformarlo a número no llegará aquí y no se copiará el dato
                        Pantalla.setText(temp);
                        this.requestFocus();
                    } catch (NumberFormatException ex) {
                    }
                }
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void jButtonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiActionPerformed
        numeroPulsado('p');
    }//GEN-LAST:event_jButtonPiActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        numeroPulsado('e');
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonAureoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAureoActionPerformed
        numeroPulsado('a');
    }//GEN-LAST:event_jButtonAureoActionPerformed

    private void jButtonEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEulerActionPerformed
        numeroPulsado('u');
    }//GEN-LAST:event_jButtonEulerActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MarcoPrincipal;
    private javax.swing.JTextField Pantalla;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonAureo;
    private javax.swing.JButton jButtonBackSpace;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCopiar;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonEuler;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMBorrar;
    private javax.swing.JButton jButtonMMas;
    private javax.swing.JButton jButtonMMenos;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonPegar;
    private javax.swing.JButton jButtonPi;
    private javax.swing.JButton jButtonPunto;
    private javax.swing.JButton jButtonRestar;
    private javax.swing.JButton jButtonSumar;
    private javax.swing.JButton jButtonVerMemo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDigitos;
    private javax.swing.JPanel jPanelMemoria;
    private javax.swing.JPanel jPanelOperaciones;
    private javax.swing.JPanel jPanelOperacionesNumeros;
    private javax.swing.JPanel jPanelTeclas;
    // End of variables declaration//GEN-END:variables
    //Portapapeles
    private Clipboard portapapeles;
    //Variable temporal para almacenar el primer operando
    private Double acumulador = 0.0;
    //Variable para guardar la operación
    private char operacion = 0;
    //Para almacenar la memoria
    Double memoria = 0.0;

    private void iniciar() {
        //Portapapeles del sistema
        portapapeles = Toolkit.getDefaultToolkit().getSystemClipboard();
        //Cambio del icono de la aplicación.
        this.setIconImage((new ImageIcon("extras/icono.jpg")).getImage());
        //Esto hace que la pantalla sea lo más pequeña posible.
        this.pack();

        //Le damos el foco a la ventana para que se detecten las teclas al pulsarlas.
        //Si captura la pulsación otro elemento no sabrá que hacer.
        this.requestFocus();
    }

    void copiarAlPortapapeles(String texto) {
        //Este objeto convierte el String de java en un objeto transferible al portapapeles
        StringSelection datos = new StringSelection(texto);
        //Copia al portapepeles el objeto transferible
        portapapeles.setContents(datos, datos);
    }

    String pegarDelPortapapeles() {
        //Si no se consigue copiar el portapapeles se devolverá una cadena vacía.
        //Si es una imagen por ejemplo no nos sirve.
        String texto = "";

        //Punto intermedio entre el portapapeles y el destino
        //Para poder tratar los datos
        Transferable datosTransferibles = portapapeles.getContents(null);

        //Con esto miramos si es una cadena de texto
        if (datosTransferibles.isDataFlavorSupported(DataFlavor.stringFlavor)) {
            try {
                //Si es una cadena intentamos copiarla a un String
                texto = (String) datosTransferibles.getTransferData(DataFlavor.stringFlavor);
            } catch (UnsupportedFlavorException ex) {
            } catch (IOException ex) {
            }
        }
        //Devolvemos lo que hemos conseguido capturar.
        return texto;
    }

    Double darValorPantalla() {
        //Transforma la cadena de texto de la pantalla en un double con el que podemos operar
        String temp = Pantalla.getText();

        try {
            //Remplazamos las comas por puntos
            temp.replace(',', '.');
            //Intenta devolver el valor en pantalla
            return Double.parseDouble(temp);
        } catch (NumberFormatException ex) {
        }

        //Si hay error devuelve un valor no operable.
        return Double.NaN;
    }

    void numeroPulsado(char tecla) {
        //Recibe el valor pulsado en pantalla o por teclado y opera de acuerdo a él.
        switch (tecla) {
            case '.': {
            }//Sin break;
            //Si no se pone el break realiza un case y a continuación el siguiente hasta que encuentra un break
            //En este caso si se pulsa un punto hace nada y pasa a realizar la acción para la coma.
            //Por tanto, es indiferente pulsar uno u otro.
            case ',': {
                if (Pantalla.getText().equalsIgnoreCase("0") || Pantalla.getText().equalsIgnoreCase("0.0")) {
                    //Si la pantalla tiene un cero
                    Pantalla.setText("0.");
                } else if (Pantalla.getText().indexOf(".") == -1) {
                    //Si no hay ningún punto ya
                    Pantalla.setText(Pantalla.getText() + ".");
                }
            }
            break;

            //Sin break
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9': {
                //Si en la pantalla hay un cero lo quitamos. Los ceros a la izquierda no cuentan
                if (Pantalla.getText().equalsIgnoreCase("0")) {
                    Pantalla.setText("");
                }
                //Si detecta un número lo coge y lo añade a la pantalla por la derecha
                Pantalla.setText(Pantalla.getText() + tecla);
            }
            break;

            //Al detectar que es una operación
            //Sin break
            case '+':
            case '-':
            case '*':
            case '/': {
                //Guarda la operación en una variable para recordarla
                //Todavía no podemos operar. Solo sabermos uno de los números.                
                operacion = tecla;
                //Guarda el primer valor que nos han dado en una variable para recordarlo.
                acumulador = darValorPantalla();
                //Borra la pantalla
                Pantalla.setText("0");
            }
            break;

                //Si pulsa enter o igual realiza la operación
            case '\n':
            case '=': {
                operar();
            }
            break;

            //Borrar backspace (último valor tecleado)
            case '\b': {
                //Solo borra si hay algo en la pantalla escrito.
                //Si solo hay un cero no hace nada.
                if (!Pantalla.getText().equals("0") && Pantalla.getText().length() > 1) {
                    //Esto borra lo último escrito en la pantalla.
                    //Lo que hay en la pantalla será la cadena actual menos el último caracter
                    Pantalla.setText(Pantalla.getText().substring(0, Pantalla.getText().length() - 1));
                } else {
                    //Si la pantalla tenía un 0 o nada pinta un 0
                    Pantalla.setText("0");
                }
            }
            break;

            //Borrar todo (tecla suprimir/delete)
            case 127: {
                //Reseteamos la calculadora
                Pantalla.setText("0");
                acumulador = 0.0;
                operacion = 0;
            }
            break;


            //Valores constantes
            case 'p': {
                Pantalla.setText("3.141592653589793");
            }
            break;

            case 'e': {
                Pantalla.setText("2.718281828459045");
            }
            break;

            case 'a': {
                Pantalla.setText("1.618033988749894");
            }
            break;

            case 'u': {
                Pantalla.setText("0.577215664901532");
            }
            break;

            //Cuando no sea ninguna de las anteriores no hará nada.
            default: {
            }
            break;
        }
        
        //Poner foco en la ventana para capturar las teclas pulsadas.
        this.requestFocus();
    }

    void operar() {
        if (operacion == '+') {
            acumulador += darValorPantalla();
        } else if (operacion == '-') {
            acumulador -= darValorPantalla();
        } else if (operacion == '*') {
            acumulador *= darValorPantalla();
        } else if (operacion == '/') {
            if (darValorPantalla() != 0) {                
                acumulador /= darValorPantalla();
            } else {
                //Si divide por 0
                Pantalla.setText("Error");
            }
        }
        
        //Mostar resultado
        Pantalla.setText(String.valueOf(acumulador));


        //Resetear el signo
        operacion = 0;

        //Quitar el decimal si es cero de la pantalla
        if (Pantalla.getText().endsWith(".0")) {
            Pantalla.setText(Pantalla.getText().substring(0, Pantalla.getText().length() - 2));
        }
    }
}
